WIP: issue 11 code coverage
hoodiehq/pouchdb-admins pull request #13
Opened 2016-06-08 04:22 UTC by kazekagegaara

Started working on `set.js` file. The test passes, but code coverage still shows that `if (error) {
          return reject(error)
        }` (line 22 in set.js) isn't covered.

2016-06-08 17:41 UTC, gr2m commented on lib/set.js
> +internals.generateSalt = require('./utils/generate-salt')
This is what I meant with exposing `internals`. This way you you do

```js
var set = require('./path/to/set')
```

then set.internals.hashPassword is accessible. That way we can mock its behavior in tests

2016-06-08 17:44 UTC, gr2m commented on tests/unit/set-test.js
> +})
when we do unit tests, then we try to only test one method at a time, in this case the `set` method. What you will see a lot in Hoodie’s code is a first argument `state`, which is passed in when initialising the API in the constructor, in this case here: https://github.com/hoodiehq/pouchdb-admins/blob/master/lib/api.js#L16

`set.bind(null, state)` will implicitly pass in the `state` argument each time someone calls `admins.set(username, password)`. So `state` is not accessible from the outside. It’s a style of functional programming. The benefit is that for testing, we can put in what ever `state` we want for the respective test case, which is very helpful

Check out unit tests of [hoodie-account-client](https://github.com/hoodiehq/hoodie-account-client/tree/master/test/unit) to see how we do unit tests.

2016-06-08 17:45 UTC, gr2m commented
Hey Manit, I pushed a few updates because I thought it would be the best way to explain. I added a few notes to the changes, I hope everything makes sense? Please let me know if you have any further questions

2016-09-11 14:56 UTC, gr2m commented
Hey @kazekagegaara, do you still want to finish this up?

2016-11-01 13:55 UTC, benwhite-deltas commented
I think this is failing because nvm 'stable' version has jumped to v7.0.0 and npm packages aren't cleaned out entirely between builds. I'll open an issue.

2016-11-03 19:02 UTC, gr2m commented
@benwhite-deltas can you rebase on master? Is this ready for review or still WIP?

2016-11-04 12:57 UTC, benwhite-deltas commented
Yeah, I'm happy to do that, when I've got 5 mins. WRT WIP, it depends - are we aiming for 100% with this PR?

2016-11-07 00:50 UTC, gr2m commented
we aim for 100% code coverage, but it doesn’t need to be all in this PR

2016-11-07 10:13 UTC, benwhite-deltas commented
Rebased, ready for review/merge.

2016-11-08 18:47 UTC, gr2m requested changes

2016-11-08 18:47 UTC, gr2m commented on tests/unit/validate-password-test.js
> +var rewire = require('rewire')
@benwhite-deltas never used [rewire](https://www.npmjs.com/package/rewire), looks good! We use [proxyquire](https://www.npmjs.com/package/proxyquire) in other projects. Do you see a benefit of one over the other? If not I’d stick with `proxyquire` to make it simpler for contributors to jump between repositories

2016-11-09 11:12 UTC, minrwhite commented on tests/unit/validate-password-test.js
> +var rewire = require('rewire')
As all things tend to be, it's a trade off.

I see `rewire` as being better when you need access to view/alter non-exported global vars defined in the module, whereas `proxyquire` allows you to handle modules that are fetched using `require()` - these are possibly intersecting but not identical sets of parameters. I also particularly like `rewire`'s `__with__` for testing purposes.

Looking at how the pull request started, I was attempting to do the kind of testing as done in set-test.js without having to expose an 'internals' object. But given that all of the objects included in that internals object are modules anyway, I agree that reducing cognitive load switching between different workflows, and refactoring to using `proxyquire` exclusively would be best.

Actioning now!

2016-11-10 04:00 UTC, gr2m approved these changes
sweet, thanks 👍 getting there :) [![Coverage Status](https://coveralls.io/repos/hoodiehq/pouchdb-admins/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/pouchdb-admins?branch=master)

2016-11-10 04:01 UTC, merged